-- MySQL Script generated by MySQL Workbench
-- Wed Oct 18 22:35:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`informacion_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`informacion_personal` (
  `id_usuario` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`admin` (
  `id_admin` VARCHAR(45) NOT NULL,
  `informacion_personal_id_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_admin`),
  UNIQUE INDEX `id_admin` (`id_admin` ASC) VISIBLE,
  INDEX `fk_admin_informacion_personal1_idx` (`informacion_personal_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_admin_informacion_personal1`
    FOREIGN KEY (`informacion_personal_id_usuario`)
    REFERENCES `proyecto`.`informacion_personal` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`estudiante` (
  `cta` VARCHAR(45) NOT NULL,
  `carrera` VARCHAR(50) NOT NULL,
  `estatus_voto` TINYINT NOT NULL DEFAULT '0',
  `informacion_personal_id_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cta`),
  UNIQUE INDEX `cta` (`cta` ASC) VISIBLE,
  INDEX `fk_estudiante_informacion_personal1_idx` (`informacion_personal_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_informacion_personal1`
    FOREIGN KEY (`informacion_personal_id_usuario`)
    REFERENCES `proyecto`.`informacion_personal` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`planilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`planilla` (
  `id_planilla` VARCHAR(45) NOT NULL,
  `nombre_planilla` VARCHAR(45) NOT NULL,
  `votos` INT NULL DEFAULT '0',
  `estudiante_cta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_planilla`),
  UNIQUE INDEX `id_planilla` (`id_planilla` ASC) VISIBLE,
  UNIQUE INDEX `nombre_planilla` (`nombre_planilla` ASC) VISIBLE,
  INDEX `fk_planilla_estudiante1_idx` (`estudiante_cta` ASC) VISIBLE,
  CONSTRAINT `fk_planilla_estudiante1`
    FOREIGN KEY (`estudiante_cta`)
    REFERENCES `proyecto`.`estudiante` (`cta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `proyecto` ;

-- -----------------------------------------------------
-- procedure getAlumnosVotos
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `getAlumnosVotos`()
BEGIN
	SELECT * FROM estudiante WHERE estatus_voto = 0;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure verificarEstatusVoto
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `verificarEstatusVoto`(IN noCta INT)
BEGIN
	SELECT estatus_voto FROM estudiante WHERE cta = noCta;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
